# Generated by Django 4.2.2 on 2024-05-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bloging", "0003_blog_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="user",
            new_name="owner",
        ),
    ]
