# Generated by Django 4.2.2 on 2024-05-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloging', '0004_rename_user_blog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='owner',
        ),
    ]
